# Generated by Django 3.2.4 on 2021-06-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210604_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completed',
            field=models.CharField(choices=[('open', 'OPEN'), ('working', 'WORKING'), ('done', 'DONE'), ('overdue', 'OVERDUE')], default='open', max_length=7, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due',
            field=models.DateField(blank=True, null=True, verbose_name='Due Date'),
        ),
    ]
